# Site settings
title: UrbanPlay
email: miwa@urbanplayfitness.org
description: "TODO - Description"
baseurl: ""
url: "http://urbanplayfitness.org"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
